backend:
  name: git-gateway
  branch: main

media_folder: "gallery"
public_folder: "/gallery"

collections:
  - name: "gallery"
    label: "معرض الصور"
    folder: "gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "الصورة", name: "image", widget: "image" }
